/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Dimension;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import paneles.CambiaPanel;
import paneles.PanelDashboard;
import paneles.PanelDesperdicio;
import paneles.PanelFinanzas;
import paneles.PanelInventario;
import paneles.PanelReporte;
import paneles.PanelSostenibilidad;
import ui.SidebarPanel;
import ui.UITheme;

/**
 *
 * @author omar.rebolledo
 */
public class EFBPrincipal extends javax.swing.JFrame {
    
    public FinanceService financeService;
    
    // PRINCIPALES COMPONENTES
    private JPanel contentPanel;
    private JPanel sidebar;
    private CardLayout cardLayout;
    
    // REFERENCIA PARA CADA PANEL.
    private PanelInventario pInventario;
    private PanelDashboard pDashboard;
    private PanelFinanzas pFinanzas;
    private PanelSostenibilidad pSostenibilidad;    
    private PanelDesperdicio pDesperdicio;    
    private PanelReporte pReporte;


    /**
     * Creates new form EFBPrincipal
     */
    public EFBPrincipal() {
        initComponents();
        
        financeService = new FinanceService();
        guardarIngreso();
        
        setTitle("EcoFinance Business - Pizzería Sostenible");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(1100, 700);
        setMinimumSize(new Dimension(900, 600));
        setLocationRelativeTo(null);
        getContentPane().setBackground(UITheme.BG);
        
        setLayout(new BorderLayout());  // === Es un tipo de distribución que divide el espacio en 5 zonas ===

        /*add(new JButton("Arriba"), BorderLayout.NORTH);
        add(new JButton("Abajo"), BorderLayout.SOUTH);
        add(new JButton("Izquierda"), BorderLayout.WEST);
        add(new JButton("Derecha"), BorderLayout.EAST);
        add(new JButton("Centro"), BorderLayout.CENTER);*/
        
        // PANEL PRINCIPAL
        cardLayout = new CardLayout();
        contentPanel = new JPanel(cardLayout);
        contentPanel.setBackground(UITheme.BG);
        
        // ========== INICIALIZO LOS PANELS =============
        pDashboard = new PanelDashboard(this);
        pFinanzas = new PanelFinanzas();
        pSostenibilidad = new PanelSostenibilidad(); 
        pInventario = new PanelInventario();    
        pDesperdicio = new PanelDesperdicio(this);
        pReporte = new PanelReporte(this);


        
        // ==== ADICIONO LOS PANELS AL PRINCIPAL
        contentPanel.add(pDashboard, "dashboard");
        contentPanel.add(pFinanzas, "finanzas");
        contentPanel.add(pSostenibilidad, "sostenibilidad");
        contentPanel.add(pInventario, "inventario");  
        contentPanel.add(pDesperdicio, "desperdicio"); 
        contentPanel.add(pReporte, "reporte");



        // inventario
        // desperdicio
        // sostenibilidad
        // reporte
        
        add(contentPanel, BorderLayout.CENTER);
        
        // SIDEBAR IZQUIERDO
        add(new SidebarPanel(route -> {
            
           /* switch(route){
                case "dashboard":
                //new CambiaPanel(contentPanel, new PanelDashboard());
                break;
                default: JOptionPane.showConfirmDialog(null, route);
            }*/
           
           //cardLayout.show(contentPanel, route);
            
            showPanel(route);
 
        }), BorderLayout.WEST);
        
    }
    
    private void guardarIngreso() {
        financeService.agregarIngreso(50000);
    }
    
    // ── Navegación ───────────────────────────────────────────────────────────
    public void showPanel(String name) {
        // Refrescar datos antes de mostrar
        /*switch (name) {
            case "dashboard":      pDashboard.refresh();      break;
            case "desperdicio":    pDesperdicio.refresh();    break;
            case "reporte":        pReporte.refresh();        break;
            case "sostenibilidad": pSostenibilidad.refresh(); break;
        }
        cardLayout.show(contentPanel, name);*/
        
        cardLayout.show(contentPanel, name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EFBPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EFBPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EFBPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EFBPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EFBPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
