/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import java.awt.BorderLayout;
import java.awt.Font;
import java.awt.GridLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import ui.UITheme;

/**
 *
 * @author omar.rebolledo
 */
public class PanelInventario extends javax.swing.JPanel {

    /**
     * Creates new form PanelDashboard
     */
    public PanelInventario() {
        initComponents();
        setBackground(UITheme.BG);
        setLayout(new BorderLayout());
        setBorder(new EmptyBorder(24, 28, 24, 28));
        build();
    }
    
    private void build(){
        add(buildPanelTitle(), BorderLayout.NORTH);
    }
    
    private JPanel buildPanelTitle(){
         // === TITLE
        JPanel top = new JPanel(new BorderLayout());
        top.setOpaque(false); // === No pintar fondo
        
        JLabel title = new JLabel("💰  Módulo 1 — Finanzas");  
        title.setFont(UITheme.FONT_EMOJI_BOLD_NORMAL);
        title.setForeground(UITheme.INK);
        
        // === SUB TITLE
         JLabel subTitle = new JLabel("Pizzería Sostenible · Vista general"); 
         subTitle.setFont(UITheme.FONT_SMALL);
         subTitle.setForeground(UITheme.MUTED);
         
         JPanel titleBox = new JPanel(new GridLayout(2, 1, 0, 2));
         titleBox.setOpaque(false);
         titleBox.add(title);
         titleBox.add(subTitle);

        top.add(titleBox, BorderLayout.WEST);
        
        return top;
    }
    
    private void content(){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
